jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug requirements
        run: cat requirements.txt

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Adjust if needed

      - name: Clear pip cache
        run: |
          rm -rf ~/.cache/pip

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run the Python script
      - name: Run Script
        env: 
          API_KEY: ${{ secrets.API_KEY }} 
        run: |
          python python/"GH-convert-for-tts-structured.py" > script_output.log 2>&1

      # Check for file changes
      - name: Check Output Changes
        run: |
          if ! git diff --quiet --exit-code; then
            echo "Changes detected."
          else
            echo "No changes detected; exiting."
            exit 0
          fi

      # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          BRANCH_NAME=$(date +'%Y-%m-%d')-convert-for-tts
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Automated changes from convert-for-tts script on $(date +'%Y-%m-%d')"
          git push origin "$BRANCH_NAME"

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.22.0/gh_2.22.0_linux_amd64.deb -o gh-cli.deb
          sudo dpkg -i gh-cli.deb
          sudo apt-get install -f

      # Create Pull Request
      - name: Create Pull Request
        run: |
          gh pr create --base main --head "$BRANCH_NAME" --title "Automated Changes on $(date +'%Y-%m-%d')" --body "This PR was created by the GitHub Actions workflow to merge the latest changes."
          gh pr merge --auto --delete-branch

      # Notify success
      - name: Notify Success
        if: success()
        run: echo "Workflow completed successfully!"

      # Notify failure
      - name: Notify Failure
        if: failure()
        run: echo "Workflow failed! Check logs for details."

      # Upload logs for debugging
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: script-log
          path: script_output.log
