name: GH Run Convert for TTS STRUCTURED

on:
  schedule:
    - cron: "30 13 */7 * 1"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug requirements
        run: cat requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Clear pip cache
        run: |
          rm -rf ~/.cache/pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Script
        env: 
          API_KEY: ${{ secrets.GH_PAT }} 
        run: |
          python python/"GH-convert-for-tts-structured.py" > script_output.log 2>&1

      - name: Check Output Changes
        id: changes
        run: |
          if git diff --quiet --exit-code; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          BRANCH_NAME=$(date +'%Y-%m-%d-%H%M%S')-json-to-lua
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Automated changes from convert-for-tts script on $(date +'%Y-%m-%d')"
          git push origin "$BRANCH_NAME"

      - name: Install GitHub CLI
        if: steps.changes.outputs.changed == 'true'
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.22.0/gh_2.22.0_linux_amd64.deb -o gh-cli.deb
          sudo dpkg -i gh-cli.deb
          sudo apt-get install -f

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        run: |
          gh pr create --base main --head "$BRANCH_NAME" --title "Automated Changes on $(date +'%Y-%m-%d')" --body "This PR was created by the GitHub Actions workflow to merge the latest changes."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Notify Success
        if: success()
        run: echo "Workflow completed successfully!"

      - name: Notify Failure
        if: failure()
        run: echo "Workflow failed! Check logs for details."

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: script-log
          path: script_output.log
